select * from v$instance;

DROP USER c##madang CASCADE;
CREATE USER c##madang 
IDENTIFIED BY madang DEFAULT TABLESPACE users TEMPORARY 
TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##madang;

GRANT CREATE VIEW, CREATE SYNONYM TO c##madang;
GRANT UNLIMITED TABLESPACE TO c##madang;
ALTER USER c##madang ACCOUNT UNLOCK;

